# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#####################
# Site configs
title: reveal.js
owner:
  name: Tankery Chen
  link: http://tankery.me
  email: tankery.chen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A framework for easily creating beautiful presentations using HTML.
baseurl: "" # the subpath of your site, e.g. /blog

# Specific social links, now we support following social account:
# github, twitter, weibo, google-plus, instagram, facebook, stack-overflow
# To support more social links, edit url in _data/socials.yml
# Remenber, always use a name that support by Font Awesome, to make sure the
# icon is shown.
socials:
  - name: github
    user: tankery
  - name: stack-overflow
    user: 1038900

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  #style: compressed


include: [".htaccess"]
exclude: ["tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "bower.json", "node_modules"]
